// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgycobxkmojbpqsbnwmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNneWNvYnhrbW9qYnBxc2Jud214Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTYxNjAsImV4cCI6MjA2NTU3MjE2MH0.VGFPGnDWcfkBnIGEtc1n1ae02BV70aA1_x5WMWLS-PY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);